### ISSUE TITLE
README Instructions don't succeed 

### ISSUE THREAD

**Issue by littlejeem** [heyValdemar/traefik-ssl-certificate-docker-swarm#1]
running docker swarm on raspberry pi 4's with gluster as a file system.

running ```sudo docker secret create wildcard-heyvaldemar-net.crt /mnt/usbstorage/docker-apps/heyvaldemar/wildcard-heyvaldemar-net.crt``` results in an error message:

```Error response from daemon: rpc error: code = InvalidArgument desc = secret data must be larger than 0 and less than 512000 bytes```

**Comment by heyvaldemar** [comment]
hey @littlejeem,

Let's discuss this on our [Discord](https://discord.gg/AJQGCCBcqf) server; it'll be more convenient.

The error message you're seeing indicates that the size of the secret data you're trying to create is either too small (0 bytes) or too large (greater than 512000 bytes). Here are a few steps to troubleshoot and potentially resolve the issue:

1. **Check the File Size**:
   Ensure that the file `/mnt/usbstorage/docker-apps/heyvaldemar/wildcard-heyvaldemar-net.crt` exists and its size is within the allowed range.

   ```bash
   ls -lh /mnt/usbstorage/docker-apps/heyvaldemar/wildcard-heyvaldemar-net.crt
   ```

   This will show you the size of the file. If it's 0 bytes, then the file is empty. If it's larger than 512KB, it's too big to be used as a Docker secret.

2. **Check File Content**:
   It's possible that the file might be empty or corrupted. You can check the contents with:

   ```bash
   cat /mnt/usbstorage/docker-apps/heyvaldemar/wildcard-heyvaldemar-net.crt
   ```

   Ensure that the content looks like a valid certificate.

3. **Filesystem Issues**:
   Since you're using GlusterFS, there could be issues related to the distributed nature of the filesystem. Ensure that the file is properly replicated and accessible from all nodes in the swarm.

4. **Alternative Approach**:
   If the file size and content seem correct, you can try creating the secret using a different method:

   ```bash
   cat /mnt/usbstorage/docker-apps/heyvaldemar/wildcard-heyvaldemar-net.crt | sudo docker secret create wildcard-heyvaldemar-net.crt -
   ```

   This command reads the content of the file and pipes it directly into the `docker secret create` command.

5. **Docker Version**:
   Ensure that you're running a compatible version of Docker on your Raspberry Pi. Sometimes, certain bugs or issues can be resolved by simply updating to the latest version.

6. **Logs & Debugging**:
   Check Docker daemon logs for any additional information or errors that might give more insight into the problem. Depending on your setup, you might find logs in the system's journal (`journalctl -u docker`) or in Docker's own log files.

If none of these steps resolve the issue, it might be worth checking for any known issues with Docker Swarm on Raspberry Pi or with the specific versions of Docker and GlusterFS you're using.

**Comment by littlejeem** [comment]
ack! I'm sorry, I've realised that the command doesn't aim to populate the file, it reads from the file and is expecting pre exisiting data. Sorry! ...wil join discord
